import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/features/shared/ui/navbar";



export const metadata: Metadata = {
  title: "MeBlazor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen antialiased max-w-[800px] mx-auto` }
      >
        <Navbar />
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}
