networks:
  appnet:
    name: appnet
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: meblazor:dev
    networks:
      - appnet
    ports:
      - 60000:8080
    environment:
      - WEATHER_API_ENDPOINT=http://backend:8080
      - ASPNETCORE_ENVIRONMENT=Development
  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: meblazor:dev
    networks:
      - appnet
    environment:
      - ALLOWED_URLS=http://web:8080
      - ASPNETCORE_ENVIRONMENT=Development
      